package com.drools.demo.point

import com.winson.tutorial.drools.bean.PointDomain;

rule subBackNumsPoint

// 发生退货，扣减10分

salience 10

lock-on-active true

when

$pointDomain : PointDomain(backNums >= 1)

then

$pointDomain.setPoint($pointDomain.getPoint()-10);

$pointDomain.recordPointLog("backNumsPoint", 10, false);

end

rule subBackMondyPoint

// 退货金额大于100，扣减100分

salience 9

lock-on-active true

when

$pointDomain : PointDomain(backMondy >= 100)

then

$pointDomain.setPoint($pointDomain.getPoint()-10);

$pointDomain.recordPointLog("backMondyPoint", 10, false);

end